### PR TITLE
Fix write_sd_card.sh script error

### PR DESCRIPTION
**Pull request by mtuxpe**
Signed-off-by: Marcio Montenegro <mtuxpe@gmail.com>

### CODE REVIEW

**Comment by jamesgraves** [comment]
I'm OK with adding the sleeps between creating the filesystems.

However, what are you trying to fix by changing the `rmdir` to `rm -rf`?  If the unmount of filesystem has been successful, then the `/mnt/sdcard_boot` and `/mnt/sdcard_rootfs` **should** be empty directories. If there is something in those directories, then the previous mount failed or there was some other problem.  That would indicate that not everything was written to the SD card correctly.

So an error at that point would indicate to the user that there was a problem.

**Comment by mtuxpe** [comment]
I think you are correct. The non-empty temporary directory in my
installation was caused by another issue.

**Comment by jamesgraves** [comment]
To keep the history a little cleaner, I made these changes and pushed it to my main branch. I did keep the `rmdir` instead of `rm` for the directory removal, because if there is an error, I want to see it.

**Comment by jamesgraves** [comment]
I should have closed this previously, since I made similar changes and committed them. Thanks for trying this out!

**Comment by jamesgraves** [comment]
I should have closed this previously, since I made similar changes and committed them. Thanks for trying this out!

**Pull request closed without merging**
